#define	GFSP_SW_VERSION			1
#define GFSP_PRODUCT_VERSION		"1.13"
#define GFSP_PRODUCT_VERSION_NUM	1, 13, 0, 8
#define GFSP_PRODUCT_UPDATE_DATE	"GFSP v1.13 , Last Updated On 13 September 2023"
#define GFSP_PRODUCT_NAME			"GFSP"
#define GFSP_PROGRAM_NAME			"GFSP.EXE"

//#define SLP_PRODUCT_UPDATE_DATE	"SLP3 v1.13 , Last Updated On 25 May 2023"
