//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// SysLinker.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_SYSLINKER_FORM              101
#define ID_DKPANE_INPUTRELAY            101
#define IDS_PROPSHT_CAPTION             102
#define ID_DKPANE_OUTPUTRELAY           103
#define ID_DKPANE_PATTERN               104
#define IDC_SP_MAIN                     105
#define IDC_PATTERNVIEW_TREE            106
#define IDC_OUTVIEW_TREE                107
#define IDC_TREELIST                    108
#define IDC_INPUTVIEW_TREE              109
#define IDB_WRITESMALL                  110
#define IDC_PUMP_TREE                   110
#define ID_DKPANE_EMERGENCY             111
#define IDB_MAIN                        112
#define ID_DKPANE_PUMP                  112
#define ID_DKPANE_PSWITCH               113
#define IDB_BUTTONS                     113
#define IDC_EMERGENCYVIEW_TREE          114
#define IDB_FILELARGE                   114
#define IDC_PUMPVIEW_TREE               115
#define IDB_FILESMALL                   115
#define IDC_PSWITCHVIEW_TREE            116
#define IDS_OUTPUT_WND                  117
#define ID_VIEW_OUTPUTWND               118
#define IDR_POPUP_EDIT                  119
#define IDS_DEBUG_TAB                   119
#define ID_STATUSBAR_PANE1              120
#define ID_CHK_VIEWDKLOG                120
#define ID_STATUSBAR_PANE2              121
#define ID_DKPANE_CONTACT               121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_DKPANE_CONTACT              124
#define IDC_CONTACTFACP_TREE            125
#define ID_SORT_LOCATION_EN             126
#define ID_SORT_ADDRESS_EN              127
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define ID_SORT_INPUTTYPE_EN            129
#define IDR_SysLinkerTYPE               130
#define ID_WINDOW_MANAGER               131
#define ID_SORT_OUTTYPE_EN              132
#define ID_VIEW_FILEVIEW                133
#define ID_DKPANE_INPUTRELAY_EN         133
#define ID_VIEW_CLASSVIEW               134
#define ID_DKPANE_OUTPUTRELAY_EN        134
#define ID_PROPERTIES                   135
#define IDS_STATUS_PANE1_EN             135
#define ID_OPEN                         136
#define IDS_STATUS_PANE2_EN             136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               151
#define IDR_WINDOWS_MENU                152
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDR_RIBBON_EN                   308
#define IDD_FORMPATTERN                 311
#define IDB_WRITELARGE                  312
#define IDD_FORMEMERGENCY               313
#define IDB_BMP_RB_LINK_LARGE           314
#define IDB_BMP_RB_LINK_SMALL           315
#define IDB_BMP_RB_SET_LARGE            316
#define IDB_BMP_RB_SET_SMALL            317
#define IDR_TB_DKPRELAY_SORT            318
#define IDR_TB_DKPRELAY_SORT1           319
#define IDR_CONTACTFACP                 320
#define IDD_DLG_NEW_PROJECT             321
#define IDR_CONT_FACP                   321
#define IDD_FORMPSWITCH                 322
#define IDD_PROP_PAGE_PRJINFO           323
#define IDD_FORMPUMP                    324
#define IDD_PROP_PAGE_DEVICETABLE       325
#define IDD_PROP_PAGE_FACP              326
#define IDD_PROP_PAGE_LOCATION          327
#define IDD_PROP_PAGE_PATTERN           328
#define IDD_PROP_PAGE_EMERGENCY         329
#define IDD_FORMSWITCH                  330
#define IDD_FORMLINKVIEW                331
#define IDD_FORMEQUIP                   332
#define IDD_FORMUSER                    333
#define IDD_FORMACCESS                  334
#define IDD_FORMLOCATION                335
#define IDB_BMP_DEVICE_ICON             336
#define IDB_BMP_CHECKS                  337
#define IDI_OUT_VIEW                    339
#define IDI_OUT_VIEW_HC                 340
#define IDI_PTRN_VIEW                   341
#define IDI_PTRN_VIEW_HC                342
#define IDD_DLG_ENV                     343
#define IDD_FORMFACP                    344
#define IDD_FORMUNIT                    345
#define IDD_FORMRELAYEDIT               346
#define IDB_BMP_PATTERN_ICON            347
#define IDC_DROPADD_CURSOR              348
#define IDD_DLG_LOGIN                   349
#define IDD_DLGCHILDPAGEBASE            350
#define IDD_DLG_MAKEAUTO_ALLINPUT       351
#define IDD_DLGCHILDBASEPAGE            352
#define IDD_DIALOG1                     353
#define IDD_SCROLLDIALOG                354
#define IDD_DLG_LINKRESULT              355
#define IDD_DLG_MAKEAUTO_ONEINPUT       356
#define IDD_DLG_MAKEAUTO_ALLINPUT1      357
#define IDD_FORMAUTOMAKE                358
#define IDR_POPUP_PTNLINK               359
#define IDR_POPUP_RELAYLINK             360
#define IDD_FORMEDITLOGIC               361
#define IDD_FORMTABLE                   362
#define IDD_DLGINFOBASEPAGE             363
#define IDD_FORMLOADRELAYTABLE          364
#define IDD_DLGINPUTCHANGE              365
#define IDD_DLGOUTPUTCHANGE             366
#define IDD_FORMPUMPEDIT                367
#define IDD_FORMPSWITCHEDIT             368
#define IDD_FORMCONTACTFACP             369
#define IDD_FORMERRORCHECK              370
#define IDD_DLG_PRJVERSION              372
#define IDD_DLG_VERSION                 374
#define IDD_DLG_SLPLOGIN                376
#define IDD_DLG_PUMPINFO                378
#define IDD_DLG_PSWITCH                 380
#define IDB_BMP_PSWITCH_TREE            382
#define IDD_DLG_TREEPANE                384
#define IDD_DLG_CHILD_RELAYTREE         387
#define IDD_DLG_CHILD_EDIT_FACP         388
#define IDD_DLG_CHILD_CHANGEVIEW        389
#define IDD_DLG_TAB_PATTERN             390
#define IDD_DLG_TAB_RELAY               391
#define IDB_BMP_EQUIP_ICON              393
#define IDD_DLG_CHILD_MAIN              396
#define IDD_DLG_CHILD_EDIT_UNIT         397
#define IDD_DLG_CHILD_EDIT_CHN          398
#define IDR_ADD_MENU                    398
#define IDD_DLG_CHILD_EDIT_RELAY        399
#define IDD_DLG_CHILD_EDIT_EMPTY        400
#define IDD_DLG_PROGRESS                401
#define IDD_DLG_PASSWORD                404
#define IDD_DLG_LOADROM                 406
#define IDB_BMP_TB_DKP_RELAY            411
#define IDD_DLG_MAKEPTN                 412
#define IDD_DLG_CUSTOM_TREE             416
#define IDD_DLG_INFO_EDIT_CHN           417
#define IDI_OUTPUT_WND                  418
#define IDD_DLG_INFO_EDIT_EMPTY         418
#define IDI_OUTPUT_WND_HC               419
#define IDD_DLG_INFO_EDIT_FACP          419
#define IDD_DLG_INFO_EDIT_UNIT          420
#define IDR_POPUP_PATTERN_VIEW          420
#define IDD_DLG_INFO_EDIT_RELAY         421
#define IDR_POPUP_EMERGENCY_VIEW        421
#define IDD_DLG_INFO_MAIN               422
#define IDR_POPUP_PUMP_VIEW             422
#define IDD_DLG_VIEW_RELAY              423
#define IDR_POPUP_PTNLIST               423
#define IDD_FORMEDITLOGIC1              424
#define IDD_DLGPATTERNCHANGE            425
#define IDD_FORMEDITLOGIC2              426
#define IDD_FORMEDITLOGIC3              427
#define IDB_CHECKBOXES                  430
#define IDD_TASKPROGRESS_DLG            433
#define IDD_PATTERN_PROPERTY            434
#define IDI_CANCEL1                     435
#define IDI_OK1                         436
#define IDI_RIGHTARROW1                 437
#define IDD_DLG_ERRORCHECK              438
#define IDD_FORMLOCATION_OLD            439
#define IDD_DIALOG_ADMIN_MODE           440
#define IDB_BMP_RB_LINK_LARGE_EDIT      442
#define IDB_BMP_RB_LINK_SMALL_EDIT      444
#define IDD_DIALOG_PROGRESS_BAR         445
#define IDD_DIALOG_ADMIN_MODE_EN        447
#define IDD_DLG_CHILD_EDIT_CHN_EN       448
#define IDD_DLG_CHILD_EDIT_FACP_EN      449
#define IDD_DLG_CHILD_EDIT_RELAY_EN     450
#define IDD_DLG_CHILD_EDIT_UNIT_EN      451
#define IDD_DLG_CHILD_MAIN_EN           452
#define IDD_DLG_CUSTOM_TREE_EN          453
#define IDD_DLG_ENV_EN                  454
#define IDD_DLG_ERRORCHECK_EN           455
#define IDD_DLG_INFO_EDIT_CHN_EN        456
#define IDD_DLG_INFO_EDIT_FACP_EN       457
#define IDD_DLG_INFO_EDIT_RELAY_EN      458
#define IDD_DLG_INFO_EDIT_UNIT_EN       459
#define IDD_DLG_INFO_MAIN_EN            460
#define IDD_DLG_LINKRESULT_EN           461
#define IDD_DLG_LOADROM_EN              462
#define IDD_DLG_LOGIN_EN                463
#define IDD_DLG_MAKEAUTO_ALLINPUT_EN    464
#define IDD_DLG_MAKEAUTO_ALLINPUT1_EN   465
#define IDD_DLG_MAKEAUTO_ONEINPUT_EN    466
#define IDD_DLG_MAKEPTN_EN              467
#define IDD_DLG_PASSWORD_EN             468
#define IDD_DLG_PRJVERSION_EN           469
#define IDD_DLG_PROGRESS_EN             470
#define IDD_DLG_PSWITCH_EN              471
#define IDD_DLG_PUMPINFO_EN             472
#define IDD_DLG_SLPLOGIN_EN             473
#define IDD_DLG_TAB_PATTERN_EN          474
#define IDD_DLG_TAB_RELAY_EN            475
#define IDD_DLG_VERSION_EN              476
#define IDD_DLG_VIEW_RELAY_EN           477
#define IDD_DLGINFOBASEPAGE_EN          480
#define IDD_FORMACCESS_EN               482
#define IDD_FORMAUTOMAKE_EN             483
#define IDD_FORMEDITLOGIC3_EN           484
#define IDD_FORMEMERGENCY_EN            485
#define IDD_FORMEQUIP_EN                486
#define IDD_FORMFACP_EN                 487
#define IDD_FORMLINKVIEW_EN             488
#define IDD_FORMLOADRELAYTABLE_EN       489
#define IDD_FORMLOCATION_EN             490
#define IDD_FORMPATTERN_EN              491
#define IDD_FORMUNIT_EN                 492
#define IDD_PATTERN_PROPERTY_EN         493
#define IDD_PROP_PAGE_DEVICETABLE_EN    494
#define IDD_PROP_PAGE_EMERGENCY_EN      495
#define IDD_PROP_PAGE_FACP_EN           496
#define IDD_PROP_PAGE_LOCATION_EN       497
#define IDD_PROP_PAGE_PATTERN_EN        498
#define IDD_PROP_PAGE_PRJINFO_EN        499
#define IDD_SYSLINKER_FORM_EN           500
#define IDR_CONT_FACP_EN                501
#define IDR_CONTACTFACP_EN              502
#define IDR_TB_DKPRELAY_SORT_EN         503
#define ID_SORT_EQUIP_EN                504
#define ID_SORT_CUSTOM_EN               505
#define ID_DKPANE_PATTERN_EN            506
#define ID_DKPANE_EMERGENCY_EN          507
#define IDR_ADD_MENU_EN                 507
#define ID_DKPANE_PUMP_EN               508
#define IDR_MAINFRAME_EN                508
#define ID_DKPANE_PSWITCH_EN            509
#define IDR_POPUP_EDIT_EN               509
#define IDS_OUTPUT_WND_EN               510
#define IDR_POPUP_EMERGENCY_VIEW_EN     510
#define ID_DKPANE_CONTACT_EN            511
#define IDR_POPUP_EXPLORER_EN           511
#define IDS_EDIT_MENU_EN                512
#define IDS_EXPLORER_EN                 513
#define IDS_DEBUG_TAB_EN                514
#define IDR_POPUP_PATTERN_VIEW_EN       515
#define IDR_POPUP_PTNLINK_EN            516
#define IDR_POPUP_PTNLIST_EN            517
#define IDR_POPUP_PUMP_VIEW_EN          518
#define IDR_POPUP_RELAYLINK_EN          519
#define IDR_POPUP_SORT_EN               520
#define IDR_SysLinkerTYPE_EN            521
#define IDR_THEME_MENU_EN               522
#define IDR_WINDOWS_MENU_EN             523
#define IDD_DIALOG_MANUAL_COPY          524
#define IDD_DIALOG_MANUAL_COPY_EN       526
#define IDC_ST_LOC                      1000
#define IDC_ED_NAME                     1001
#define IDC_ED_SITE                     1002
#define IDC_LST_TABLE                   1002
#define IDC_STATIC_2                    1002
#define IDC_ED_CREATEDATE               1003
#define IDC_BROWSER                     1003
#define IDC_STATIC_3                    1003
#define IDC_ED_MAKER                    1004
#define IDC_BTN_ADD                     1004
#define IDC_STATIC_4                    1004
#define IDC_ED_SITE_MANAGER_PHONE       1005
#define IDC_BTN_DEL                     1005
#define IDC_STATIC_5                    1005
#define IDC_ED_MODIFYDATE               1005
#define IDC_TREE1                       1006
#define IDC_LOC_TREE                    1006
#define IDC_BTN_BROWSER                 1006
#define IDC_PATTERN_TREE                1006
#define IDC_LOCATION_TREE               1006
#define IDC_PROJECT_TREE                1006
#define IDC_TREE                        1006
#define IDC_BTN_CANCEL                  1006
#define IDC_BTN_LOAD                    1006
#define IDC_BTN_LOGIC_IMPORT            1006
#define IDC_ED_PRJ_VERSION              1007
#define IDC_LIST1                       1007
#define IDC_DEVICE_LIST                 1007
#define IDC_IN_TREE                     1007
#define IDC_ED_BUILD                    1007
#define IDC_SP_LEFT                     1007
#define IDC_ED_DATABASE                 1008
#define IDC_CHECK1                      1008
#define IDC_CHK_PATTERN                 1008
#define IDC_CHK_IN_BUILD                1008
#define IDC_OUT_TREE                    1008
#define IDC_ED_MODIFIER                 1008
#define IDC_AFTER_LIST                  1008
#define IDC_ED_PRJ_VERSION2             1008
#define IDC_CHK_ALLFLOOR                1008
#define IDC_ED_STAIR                    1008
#define IDC_LIST_TYPE                   1008
#define IDC_SP_RIGHT                    1008
#define IDC_ED_PRJ_PATH                 1009
#define IDC_CHECK2                      1009
#define IDC_CHKP_BUILD                  1009
#define IDC_ED_PORT                     1009
#define IDC_CHK_IN_FLOOR                1009
#define IDC_ED_DATABASE2                1009
#define IDC_CHK_CURRENTFLOOR            1009
#define IDC_ED_FLOOR                    1009
#define IDC_ED_SITE_MANAGER             1010
#define IDC_CHECK3                      1010
#define IDC_CHK_IN_ROOM                 1010
#define IDC_CHK_UNDERFLOOR              1010
#define IDC_CHECK4                      1011
#define IDC_CHKP_STAIR                  1011
#define IDC_CHK_IN_INPUTTYPE            1011
#define IDC_ED_PRJ_PATH2                1011
#define IDC_CHK_UPPERFLOOR              1011
#define IDC_CHK_PARKING                 1011
#define IDC_CHECK5                      1012
#define IDC_CHK_BUILD                   1012
#define IDC_CHKP_ROOM                   1012
#define IDC_CHKE_BUILD                  1012
#define IDC_CHK_IN_EQUIP                1012
#define IDC_CHK_EMERGENCY               1012
#define IDC_CHECK6                      1013
#define IDC_CHK_LEVEL                   1013
#define IDC_CHKP_LEVEL                  1013
#define IDC_ED_ADDR                     1013
#define IDC_CHK_IN_BTYPE                1013
#define IDC_CHK_OUTPUT                  1013
#define IDC_CHECK7                      1014
#define IDC_CHKP_LEVEL_BUILD            1014
#define IDC_CHKE_BTYPE                  1014
#define IDC_CHK_IN_STAIR                1014
#define IDC_BTN_LOGIC_EXPORT            1014
#define IDC_CHECK8                      1015
#define IDC_CHKP_STAIR_BUILD            1015
#define IDC_CHKE_STAIR                  1015
#define IDC_ED_USER                     1015
#define IDC_USE_BUID_MATCH              1015
#define IDC_CHECK9                      1016
#define IDC_CHKP_STAIR_LEVEL            1016
#define IDC_CHKP_LEVEL_STAIR            1016
#define IDC_ST_SERVER3                  1016
#define IDC_USE_STAIR_MATCH             1016
#define IDC_CHECK10                     1017
#define IDC_CHK_LEVEL_BUILD             1017
#define IDC_CHKP_ROOM_BUILD             1017
#define IDC_ST_SERVER4                  1017
#define IDC_USE_LEVEL_MATCH             1017
#define IDC_CHECK11                     1018
#define IDC_CHK_STAIR                   1018
#define IDC_CHKP_ROOM_LEVEL             1018
#define IDC_CHK_ROOM                    1018
#define IDC_CMB_BAUDRATE                1018
#define IDC_USE_BTYPE_MATCH             1018
#define IDC_CHECK12                     1019
#define IDC_CHK_STAIR_BUILD             1019
#define IDC_CHK_EQUIP_BUILD             1019
#define IDC_CHK_ROOM_BUILD              1019
#define IDC_CMB_STOPBIT                 1019
#define IDC_USE_ROOM_MATCH              1019
#define IDC_CHECK13                     1020
#define IDC_CHK_STAIR_LEVEL             1020
#define IDC_CHK_EQUIP_LEVEL             1020
#define IDC_CHK_ROOM_STAIR              1020
#define IDC_ST_SERVER5                  1020
#define IDC_CHK_UNDERFLOOR_CLASS_DONG   1020
#define IDC_EMB_LIST                    1021
#define IDC_CHK_LEVEL2                  1021
#define IDC_CHK_BTYPE                   1021
#define IDC_ST_SERVER6                  1021
#define IDC_CHK_UNDERFLOOR_CLASS_STAIR  1021
#define IDC_PATTERN_LIST                1022
#define IDC_CHKE_BTYPE_BUILD            1022
#define IDC_ED_PWD                      1022
#define IDC_CHK_UNDERFLOOR_FIRST_FLOOR  1022
#define IDC_CHK_EQUIP                   1023
#define IDC_CHKE_STAIR_BUILD            1023
#define IDC_CMB_PARITY                  1023
#define IDC_RELAY_LIST                  1023
#define IDC_CHK_UNDERFLOOR_B1F          1023
#define IDC_ST_FRAME                    1024
#define IDC_CHKP_LEVEL_BUILD2           1024
#define IDC_CHKP_BTYPE_BUILD            1024
#define IDC_CHKE_STAIR_BTYPE            1024
#define IDC_CMB_DATABIT                 1024
#define IDC_CHKP_MATCH_BUILD            1024
#define IDC_CHK_PARKING_CLASS_DONG      1024
#define IDC_CHK_UNDER_PARKING           1024
#define IDC_BTN_PREVIEW                 1025
#define IDC_ED_DBPORT                   1025
#define IDC_CHKP_MATCH_BTYPE            1025
#define IDC_CHK_PARKING_CLASS_STAIR     1025
#define IDC_ED_PATH                     1026
#define IDC_CHKP_LEVEL_BTYPE            1026
#define IDC_CHK_LEVEL_BTYPE             1026
#define IDC_CHKP_MATCH_STAIR            1026
#define IDC_BTN_APPLY                   1026
#define IDC_CHK_PARKING_B1F             1026
#define IDC_CHKP_STAIR_BTYPE            1027
#define IDC_CHK_LEVEL_STAIR             1027
#define IDC_CHKP_MATCH_FLOOR            1027
#define IDC_CHK_PARKING_FIRST_FLOOR     1027
#define IDC_CHKP_ROOM_BTYPE             1028
#define IDC_CHK_ROOM_BTYPE              1028
#define IDC_BTN_SAVE                    1028
#define IDC_CHKP_MATCH_ROOM             1028
#define IDC_CHKP_EQUIP_BTYPE            1029
#define IDC_CHK_ROOM_LEVEL              1029
#define IDC_COMBO1                      1029
#define IDC_CMB_PROJECT                 1029
#define IDC_BTN_MAKE                    1029
#define IDC_CMB_INTYPE                  1029
#define IDC_BTN_SAVE2                   1029
#define IDC_CHKP_ROOM_STAIR             1030
#define IDC_CMB_IN_TO_BUILD             1030
#define IDC_CMB_CHN                     1030
#define IDC_BTN_STOP                    1030
#define IDC_CHK_UNDERFLOOR_CLASS_BTYPE  1030
#define IDC_CHKP_EQUIP_STAIR            1031
#define IDC_CMB_IN_FROM_FLOOR           1031
#define IDC_CMB_BUILD                   1031
#define IDC_CMB_EQNAME                  1031
#define IDC_CMB_IN_TO_FLOOR             1032
#define IDC_CMB_STAIR                   1032
#define IDC_CMB_OUTCONTENTS             1032
#define IDC_BTN_IN_SEARCH_ROOM          1033
#define IDC_CMB_ROOM                    1033
#define IDC_CHK_SAME_OUTPUT             1033
#define IDC_ED_IN_VIEW_ROOM             1034
#define IDC_CMB_EQUIPNAME               1034
#define IDC_BTN_IN_SEARCH_INPUTTYPE     1035
#define IDC_CMB_CONTENTS                1035
#define IDC_ED_IN_VIEW_INPUTTYPE        1036
#define IDC_BTN_IN_SEARCH_EQUIP         1037
#define IDC_ED_IN_VIEW_EQUIP            1038
#define IDC_CHKP_MATCH_EQUIP            1039
#define IDC_CMB_BTYPE                   1039
#define IDC_CHK_OUT_BUILD               1040
#define IDC_CMB_FLOOR                   1040
#define IDC_CHK_OUT_FLOOR               1041
#define IDC_CHK_OUT_ROOM                1042
#define IDC_CMB_INPUTTYPE               1042
#define IDC_CMB_OUT_FROM_BUILD          1043
#define IDC_CMB_OUTTYPE                 1043
#define IDC_CMB_OUT_TO_BUILD            1044
#define IDC_CMB_PATTERN                 1044
#define IDC_CMB_OUT_FROM_FLOOR          1045
#define IDC_CMB_OUT_TO_FLOOR            1046
#define IDC_BTN_OUT_SEARCH_ROOM         1047
#define IDC_ED_OUT_VIEW_ROOM            1048
#define IDC_CHK_OUT_OUTPUTTYPE          1049
#define IDC_BTN_OUT_SEARCH_OUTPUTTYPE   1050
#define IDC_ED_OUT_VIEW_OUTPUTTYPE      1051
#define IDC_CHK_OUT_EQUIP               1052
#define IDC_BTN_OUT_SEARCH_EQUIP        1053
#define IDC_ED_OUT_VIEW_EQUIP           1054
#define IDC_BTN_IN_SEARCH_BTYPE         1055
#define IDC_ED_IN_VIEW_BTYPE            1056
#define IDC_CHK_OUT_BTYPE               1057
#define IDC_BTN_PREVIEW_INPUT           1058
#define IDC_BTN_PREVIEW_OUTPUT          1059
#define IDC_BTN_PREVIEW_LINK            1060
#define IDC_BTN_OUT_SEARCH_BTYPE        1061
#define IDC_ED_OUT_VIEW_BTYPE           1062
#define IDC_BTN_IN_SEARCH_STAIR         1063
#define IDC_ED_IN_VIEW_STAIR            1064
#define IDC_CHK_OUT_STAIR               1065
#define IDC_BTN_OUT_SEARCH_STAIR        1066
#define IDC_STATIC_1                    1067
#define IDC_ED_OUT_VIEW_STAIR           1067
#define IDC_ST_FRAME2                   1068
#define IDC_CMB_IN_FROM_BUILD           1069
#define IDC_ST_PREVIEW_FRAME            1070
#define IDC_BTN_RELAY_DEL               1074
#define IDC_ED_PTN_NAME                 1075
#define IDC_ED_PTN_CODE                 1076
#define IDC_BTN_DICT_ADD                1076
#define IDC_ED_PTN_ID                   1077
#define IDC_ACCESS_TREE                 1078
#define IDC_BTN_RELAY_ADD               1078
#define IDC_SCREEN_LIST                 1079
#define IDC_ED_PTN_CNT                  1079
#define IDC_EQUIP_TREE                  1080
#define IDC_BTN_DICT_DEL                1081
#define IDC_ED_EQUIP_NAME               1082
#define IDC_CMB_EQUIPTYPE               1083
#define IDC_ED_EQUIP_ID                 1084
#define IDC_DICTIONARY_LIST             1085
#define IDC_ED_UNIT_NUM                 1085
#define IDC_ED_EQUIP_SYMBOL             1085
#define IDC_SWITCH_LIST                 1086
#define IDC_CMB_FACP                    1087
#define IDC_BTN_VIEW                    1088
#define IDC_CMB_UNIT                    1088
#define IDC_ED_FACP_NAME                1089
#define IDC_FACP_LIST                   1090
#define IDC_CMB_FACP_TYPE               1091
#define IDC_ED_FACP_NUM                 1092
#define IDC_EMERGENCY_TREE              1094
#define IDC_EMERGENCY_LIST              1095
#define IDC_UNIT_TREE                   1096
#define IDC_UNIT_LIST                   1097
#define IDC_ED_UNIT_NAME                1098
#define IDC_CMB_UNIT_TYPE               1099
#define IDC_ED_UNIT_ID                  1100
#define IDC_CMB_PTN_TYPE                1101
#define IDC_VERSION_LIST                1102
#define IDC_ST_DEVICE                   1103
#define IDC_BTN_ENV                     1104
#define IDC_BTN_REFRESH                 1105
#define IDC_BTN_EXCEL                   1106
#define IDC_ED_NUM                      1107
#define IDC_ED_DESK                     1108
#define IDC_ED_ADDNUM                   1108
#define IDC_ENV_PRJPATH                 1109
#define IDC_CMB_PSTYPE                  1110
#define IDC_EFFECT_TAB                  1111
#define IDC_BEFORE_LIST                 1112
#define IDC_ST_PREVIEW                  1116
#define IDC_DEVICE_TREE                 1117
#define IDC_CMB_TYPE                    1119
#define IDC_PROG                        1120
#define IDC_ST_INFO                     1121
#define IDC_ST_MESSAGE                  1124
#define IDC_ED_INPUT                    1125
#define IDC_ED_RESULT                   1126
#define IDC_ED_ROM                      1130
#define IDC_LOGIC_LIST                  1132
#define IDC_ED_PLUSNFLOOR               1133
#define IDC_CHKP_BTYPE                  1135
#define IDC_LIST_USER                   1137
#define IDC_TAB                         1138
#define IDC_STATIC_SLIT_PANE            1139
#define IDC_MFCEDITBROWSE1              1141
#define IDC_PROGRESS                    1143
#define IDC_RD_ADDR                     1144
#define IDC_RD_NAME                     1145
#define IDC_LIST_PATTERN                1145
#define IDC_LIST_RELAY                  1146
#define IDC_PROG_STEP                   1146
#define IDC_LIST_INPUT                  1148
#define IDC_ED_TABLE                    1150
#define IDC_LB_PATH                     1151
#define IDC_ST_PART                     1152
#define IDC_ST_ALL                      1153
#define IDC_TASK_LIST                   1155
#define IDC_PROG_JOB                    1156
#define IDC_ST_PROG_STATUS              1157
#define CG_IDC_PROGDLG_PERCENT          1158
#define IDC_RD_MANAUL_MAKE              1159
#define IDC_RD_TABLE_MAKE               1160
#define IDC_ST_VERSION                  1160
#define IDC_LIST_REPORT                 1163
#define IDC_EDIT_PASSWORD               1166
#define IDC_LIST_NEW_MODULE_TABLE       1167
#define IDC_BTN_DELETE                  1168
#define IDC_PROGRESS1                   1169
#define IDC_STATIC_MESSAGE              1170
#define IDC_BUTTON_COPY                 1173
#define IDC_BUTTON_PASTE                1174
#define IDC_EDIT_INPUT                  1176
#define IDC_ED_SEARCH                   1177
#define IDC_BTN_SEARCH                  1178
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_HOME_PROJECT_NEW             32772
#define ID_HOME_PROJECT_OPEN            32773
#define ID_HOME_PROJECT_SAVE            32774
#define ID_HOME_PROJECT_CLOSE           32775
#define ID_BASIC_ENVSET                 32776
#define ID_FACP_CREATE_LINK             32777
#define ID_FACP_REVERSE_LINK            32778
#define ID_HOME_LOGIN                   32779
#define ID_FACP_EDIT_LINK               32780
#define ID_FACP_LINK_PUMP               32781
#define ID_FACP_LINK_PS                 32782
#define ID_FACP_EMMERGENCY              32783
#define ID_FACP_PATTERN                 32784
#define ID_FACP_LOCATION                32785
#define ID_FACP_PREVIEW_LINK            32786
#define ID_FACP_SET_FACPPWD             32787
#define ID_BASIC_SET_USER               32790
#define ID_BASIC_SET_USERGROUP          32791
#define ID_BASIC_SET_DRAW               32792
#define ID_BASIC_SET_ACCESSLEVEL        32793
#define ID_BASIC_SET_INOUT_TYPE         32794
#define ID_BASIC_SET_PUMP               32795
#define ID_BASIC_SET_FACP               32796
#define ID_BASIC_SET_UNIT               32797
#define ID_BASIC_SET_EQUIP              32798
#define ID_SORT_LOCATION                32799
#define ID_SORT_ADDRESS                 32800
#define ID_SORT_INPUTTYPE               32801
#define ID_SORT_OUTTYPE                 32802
#define ID_SORT_EQUIP                   32803
#define ID_SORT_CUSTOM                  32804
#define ID_HOME_VIEWINPUTRELAY          32805
#define ID_BASIC_SET_ENV                32806
#define ID_PTNLINKPOPUP_32807           32807
#define ID_PTNLINKPOPUP_32808           32808
#define ID_PTNLK_MENU_DELPTN            32809
#define ID_PTNLK_MENU_VIEWPTN           32810
#define ID_RLYLINKMENU_32811            32811
#define ID_RLYLK_MENU_DELRLY            32812
#define ID_RLYLK_MENU_VIEWRELAY         32813
#define ID_CHK_VIEWDKOUTPUT             32814
#define ID_CHK_VIEWDKPATTERN            32815
#define ID_CHK_VIEWDKINPUT              32816
#define ID_FACP_RELAYEDIT               32817
#define IDC_ADD_FACP                    32818
#define IDC_ADD_UNIT                    32819
#define IDC_ADD_CHN                     32820
#define IDC_ADD_RELAY                   32821
#define ID_CHK_VIEWDKPUMP               32822
#define ID_CHK_VIEWDKEMERGENCY          32823
#define ID_CHK_VIEWDKPSWITCH            32824
#define ID_BASIC_SET_LOGIC_EDIT         32825
#define ID_BUTTON2                      32827
#define ID_ERROR_CHECK                  32827
#define ID_BUTTON3                      32830
#define ID_HOME_PROJECT_TABLE           32830
#define ID_BUTTON4                      32831
#define ID_BUTTON7                      32834
#define ID_RLYLK_MENU_MOVERELAY         32836
#define ID_MOVE_PATTERNVIEW             32837
#define ID_PTNVIEW_SELECT_ITEM          32838
#define ID_                             32839
#define ID_HOME_ERROR_CHECK             32839
#define ID_EMBCVIEW_SELECT_ITEM         32840
#define ID_PTNVIEW_                     32841
#define ID_PSVIEW_SELECT_ITEM           32842
#define ID_PUMPVIEW_SELECT_ITEM         32843
#define ID_POPUP_PTNLIST_DEL            32844
#define ID_ITEM_                        32845
#define ID_ITEM_SELECT_ITEM             32846
#define ID_CHK_VIEWDKCONTACT            32848
#define ID_LOAD_CONTACT                 32849
#define ID_BUTTON32850                  32850
#define ID_LOAD_CONTACTFACP             32852
#define ID_LOAD_CONTACTFACP2            32853
#define ID_LOAD_CONTACTFACP_EN          32853
#define ID_CHK_SHOWHELPMSG              32855

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        527
#define _APS_NEXT_COMMAND_VALUE         32856
#define _APS_NEXT_CONTROL_VALUE         1179
#define _APS_NEXT_SYMED_VALUE           371
#endif
#endif
